[tool.mypy]
strict = false
exclude = [
    "^venv/.*$",
    "^migrations/.*$",
    "^tests/.*$",
]
plugins = [
  "pydantic.mypy"
]
[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.ruff]
exclude =[
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "venv",
    ".venv",
    ".env",
    ".idea",
    "migrations"
]
line-length = 79
target-version = "py310"


[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = [
    # pycodestyle
    #"E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    #"B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[lint.extend-per-file-ignores]
"__init__.py" = ["F401"]


[tool.pytest.ini_options]
testpaths = [
    "tests",
]
python_files = "test_*.py"
pythonpath = ["."]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
#log_cli = true
#log_cli_level = "DEBUG






















