[tool.ruff]
exclude =[
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "venv",
    ".venv",
    ".env",
    ".idea"
]
line-length = 79
target-version = "py310"

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint.isort]
case-sensitive = true

[tool.ruff.lint]
ignore = []

[tool.mypy]
strict = false
exclude = [
    "^venv/.*$",
    "^migrations/.*$",
    "^tests/.*$",
]
plugins = [
  "pydantic.mypy"
  ]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true


[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["F401"]

























